### PR TITLE
Fix incorrect path normalization

### LINKED ISSUE #20: Incorrect path normalization of some abnormal examples from Section 5.4.2
Hi there --

While I was finishing up writing tests for #19, I noticed that the `normpath` function doesn't correctly handle two of the abnormal examples mentioned in [RFC 3986 Section 5.4.2](https://tools.ietf.org/html/rfc3986#section-5.4.2):

```julia
julia> # The following is supposed to come out as http://a/b/c/g.

julia> URIs.normpath("http://a/b/c/g.")
"http://a/b/c/g./"

julia> # The following is supposed to come out as http://a/b/c/g..

julia> URIs.normpath("http://a/b/c/g..")
"http://a/b/c/g../"
```

### PR DESCRIPTION
**Pull request by kernelmethod**
This pull request fixes #20, by rewriting the `normpath` routine to operate more closely to its corresponding function in IETF RFC 3986 (the `remove_dot_segments` function described in Sec. 5.2.4).

In addition to rewriting `normpath`, I've added the "abnormal" test cases that triggered #20 to the test suite for `normpath`. I've also added the full list of abnormal test cases described in Sec. 5.4 for the `resolvereference` function, including the erroneous case, which should hopefully help catch errors like this more often.

Closes #20.

### CODE REVIEW

File: src/URIs.jl [hunk 1]
```diff
@@ -453,31 +455,54 @@ normpath(url::URI) =
     URI(scheme=url.scheme, userinfo=url.userinfo, host=url.host, port=url.port,
         path=normpath(url.path), query=url.query, fragment=url.fragment)
 
+# normpath helper functions
+_tail(s, prefix) = last(s, length(s) - length(prefix))
+function _pop_segment(buf)
+    last_slash = findlast('/', buf)
+    (last_slash === nothing) ? "" : first(buf, last_slash-1)
```
Comment (fonsp) [inline src/URIs.jl:462]:
```suggestion
    (last_slash === nothing) ? "" : buf[1:prevind(buf, last_slash)]
```

This will fix incorrect behaviour when using non-ASCII characters, e.g.

```
@test _pop_segment("a/b") == "a"
@test _pop_segment("🌟/🌟") == "🌟"
```

We should also add a couple of tests that use non-ASCII characters.

**Review by fonsp — CHANGES_REQUESTED** [review]
This is **AWESOME** work, thank you so much! 👍👍

I reviewed the implementation and the tests, both are following the spec exactly. Really nice!

File: src/URIs.jl (hunk 1 above)
Comment (fonsp) [reply src/URIs.jl:462]: RFC 3986 says that such characters should have been percent-encoded during construction, so this edge case shouldn't occur. 

```js
// JS
> new URL("https://a/🌟/e").pathname
"/%F0%9F%8C%9F/e"
```

```julia
julia> URI("https://a/🌟/e").path
"/🌟/e"
```

Let's make a new issue and go from there?

Comment (kernelmethod) [reply src/URIs.jl]: I've gone ahead and incorporated your suggestion since it seems to be the better way of doing this in any case, but you're right -- URIs, as specified by RFC 3986, are only supposed to include US-ASCII characters. If we wanted to support Unicode we'd have to implement [RFC 3987](https://datatracker.ietf.org/doc/html/rfc3987), which specifies Internationalized Resource Identifiers (IRIs).

**Review by fonsp — APPROVED** [review]

File: src/URIs.jl [hunk 2]
```diff
@@ -453,31 +455,54 @@ normpath(url::URI) =
     URI(scheme=url.scheme, userinfo=url.userinfo, host=url.host, port=url.port,
         path=normpath(url.path), query=url.query, fragment=url.fragment)
 
+# normpath helper functions
+_tail(s, prefix) = last(s, length(s) - length(prefix))
+function _pop_segment(buf)
+    last_slash = findlast('/', buf)
+    (last_slash === nothing) ? "" : buf[begin:prevind(buf, last_slash)]
```
Comment (quinnj) [inline src/URIs.jl:462]: The `buf[begin:...]` syntax isn't valid for 1.0 (hence the failing CI tests). I'd be fine bumping up the required Julia version to 1.6, since that's the new LTS, or I think we could change this to `buf[firstindex(buf):...]`.

Comment (kernelmethod) [reply src/URIs.jl]: Sorry for the delay, I've gone ahead and updated the code to use `firstindex` instead of `begin` for backwards compatibility. But yeah, since 1.0 isn't supported anymore, I'm not sure how big an issue it is.

**Comment by quinnj** [comment]
Oops, sorry this slipped through the cracks on getting merged! Thanks @kernelmethod!
